site_name: CTF Note
site_description: CTF 学习笔记
site_url: https://jiuchengovo.github.io/

theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: 切换深色模式
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: 切换浅色模式

markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - 首页: index.md
  - Lab 0: Crypto Lab 0.md
  - "Lab 1":
      - "Crypto": Crypto Lab 1.md
      - "Web": "Lab 1：Web.md"
      - "Web基础知识": Web_Lab1.md
      - "Pwn": Pwn.md
      - "Misc": "Lab 1 Misc.md"
      - "Reverse": "rev lab 1.md"
  - "Lab 2":
      - "Crypto": Crypto Lab 2.md
      - "Misc": Misc Lab 2.md
  - "Lab 3":
      - "Crypto": Crypto Lab 3.md
      - "Misc": Misc Lab 3.md

plugins:
  - search
